AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  EnabledByDefault: true
  Exclude:
    - 'pkg/**/*'
    - 'coverage/**/*'

require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake

Layout/LineLength:
  Max: 100

# We have a lot of portuguese examples in the comments so...
Style/AsciiComments:
  Enabled: false

# The default (10) is too litle
Metrics/MethodLength:
  Max: 15

# Blocks in spec files get big
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# We want to support older versions of ruby
Style/ExpandPathArguments:
  Enabled: false

RSpec/AlignLeftLetBrace:
  Enabled: false

RSpec/AlignRightLetBrace:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Lint/ConstantResolution:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/MissingElse:
  Enabled: false

Style/Copyright:
  Enabled: false
